apiVersion: v1
kind: Namespace
metadata:
  name: clahanstore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: clahanstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: clahanstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: vignesh8386/order-service:latest
        ports:
        - containerPort: 3008
        env:
        - name: PORT
          value: '3008'
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: clahanstore-config
              key: MONGO_URI_ORDER
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: clahanstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: vignesh8386/payment-service:latest
        ports:
        - containerPort: 3009
        env:
        - name: PORT
          value: '3009'
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: clahanstore-config
              key: ORDER_SERVICE_URL
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: clahanstore-config
              key: MONGO_URI_PAYMENT
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-service
  namespace: clahanstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-service
  template:
    metadata:
      labels:
        app: invoice-service
    spec:
      containers:
      - name: invoice-service
        image: vignesh8386/invoice-service:latest
        ports:
        - containerPort: 3010
        env:
        - name: PORT
          value: '3010'
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: clahanstore-config
              key: ORDER_SERVICE_URL
        - name: PAYMENT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: clahanstore-config
              key: PAYMENT_SERVICE_URL
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: clahanstore-config
              key: MONGO_URI_INVOICE
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: clahanstore
spec:
  selector:
    app: order-service
  ports:
  - port: 3008
    targetPort: 3008
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: clahanstore
spec:
  selector:
    app: payment-service
  ports:
  - port: 3009
    targetPort: 3009
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: invoice-service
  namespace: clahanstore
spec:
  selector:
    app: invoice-service
  ports:
  - port: 3010
    targetPort: 3010
  type: ClusterIP