apiVersion: apps/v1
kind: Deployment
metadata:
  name: ey-cart-deployment
  namespace: akash-ns
  labels:
    app: cart
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: ey-cart-container
        image: muralisocial123/ey-cart:v1.1.0
        ports:
        - containerPort: 3000