apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: raj-pod-access
  namespace: clahanstore
subjects:
- kind: User
  name: raj
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: my-sa
  namespace: clahanstore
  #apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: sa-demo
  apiGroup: rbac.authorization.k8s.io