apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: allow-only-dockerhub-library
  namespace: secure-ns
spec:
  validationFailureAction: Enforce
  rules:
  - name: check-image-registry
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Only official Docker Hub images are allowed"
      anyPattern:
      - spec:
          containers:
          - image: "docker.io/library/*"
      - spec:
          containers:
          - image: "library/*"
      - spec:
          containers:
          - image: "*"