apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: akash-ns
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: env
                operator: In
                values:
                - testing

          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: envs
                operator: In
                values:
                - test

      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80